name: Dependency Vulnerability Check

on:
  schedule:
    - cron: '0 10 * * 1' # Run every Monday at 10:00 UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      id: dependency-check
      with:
        project: 'deptrast'
        path: '.'
        format: 'HTML'
        out: 'dependency-check-report'
    
    - name: Upload Report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: ${{ github.workspace }}/dependency-check-report/