name: Dependency Vulnerability Check

on:
  schedule:
    - cron: '0 10 * * 1'  # Run every Monday at 10:00 UTC
  workflow_dispatch:       # Allow manual triggering
  push:
    paths:
      - 'pom.xml'         # Run when dependencies change

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    # Dedicated cache for dependency-check data
    - name: Cache dependency-check data
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository/org/owasp/dependency-check-data
        key: ${{ runner.os }}-dependency-check-data-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-dependency-check-data-

    # Run dependency check with multiple report formats
    - name: Run OWASP Dependency Check
      id: dependency-check
      continue-on-error: true  # Continue workflow even if vulnerabilities are found
      run: |
        mvn org.owasp:dependency-check-maven:8.4.3:check \
          -Dformats=HTML,JSON \
          -DoutputDirectory=dependency-check-report \
          -DautoUpdate=true \
          -DfailBuildOnCVSS=11

    # Upload HTML report as artifact
    - name: Upload HTML Report
      if: always()  # Run even if previous step fails
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report-html
        path: dependency-check-report/dependency-check-report.html
        
    # Upload JSON report as artifact
    - name: Upload JSON Report
      if: always()  # Run even if previous step fails
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report-json
        path: dependency-check-report/dependency-check-report.json